// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using SyllabusManager.Data.ProviderContexts;

namespace SyllabusManager.Data.Migrations.Oracle
{
    [DbContext(typeof(OracleSyllabusManagerDbContext))]
    partial class OracleSyllabusManagerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Name")
                        .HasColumnType("NVARCHAR2(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("NVARCHAR2(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("NVARCHAR2(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("Name")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("Value")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("SyllabusManager.Data.Models.FieldOfStudies.FieldOfStudy", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("BranchOfScience")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Discipline")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Faculty")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("NUMBER(1)");

                    b.Property<int>("Language")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("Level")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("Profile")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("SupervisorId")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<int>("Type")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Code");

                    b.HasIndex("SupervisorId");

                    b.ToTable("FieldsOfStudies");
                });

            modelBuilder.Entity("SyllabusManager.Data.Models.FieldOfStudies.Specialization", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("FieldOfStudyCode")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Code");

                    b.HasIndex("FieldOfStudyCode");

                    b.ToTable("Specialization");
                });

            modelBuilder.Entity("SyllabusManager.Data.Models.LearningOutcomes.LearningOutcome", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("RAW(16)");

                    b.Property<int>("Category")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Description")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<Guid?>("LearningOutcomeDocumentId")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("S2degreePrk")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("S2degreePrkeng")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("SpecializationCode")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("U1degreeCharacteristics")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.HasIndex("LearningOutcomeDocumentId");

                    b.HasIndex("SpecializationCode");

                    b.ToTable("LearningOutcome");
                });

            modelBuilder.Entity("SyllabusManager.Data.Models.LearningOutcomes.LearningOutcomeDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("AcademicYear")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("FieldOfStudyCode")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.HasIndex("FieldOfStudyCode");

                    b.ToTable("LearningOutcomeDocuments");
                });

            modelBuilder.Entity("SyllabusManager.Data.Models.Subjects.CardEntries", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<Guid?>("SubjectId")
                        .HasColumnType("RAW(16)");

                    b.Property<int>("Type")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.ToTable("CardEntries");
                });

            modelBuilder.Entity("SyllabusManager.Data.Models.Subjects.CardEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("RAW(16)");

                    b.Property<Guid?>("CardEntriesId")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Description")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.HasIndex("CardEntriesId");

                    b.ToTable("CardEntry");
                });

            modelBuilder.Entity("SyllabusManager.Data.Models.Subjects.ClassForm", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Description")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("Hours")
                        .HasColumnType("NUMBER(10)");

                    b.Property<Guid?>("LessonId")
                        .HasColumnType("RAW(16)");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.ToTable("ClassForm");
                });

            modelBuilder.Entity("SyllabusManager.Data.Models.Subjects.LearningOutcomeEvaluation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Description")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("GradingSystem")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("LearningOutcomeSymbol")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<Guid?>("SubjectId")
                        .HasColumnType("RAW(16)");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.ToTable("LearningOutcomeEvaluation");
                });

            modelBuilder.Entity("SyllabusManager.Data.Models.Subjects.Lesson", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("RAW(16)");

                    b.Property<int>("Ects")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("EctsinclDirectTeacherStudentContactClasses")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("EctsinclPracticalClasses")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("FormOfCrediting")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("HoursAtUniversity")
                        .HasColumnType("NUMBER(10)");

                    b.Property<bool>("IsFinal")
                        .HasColumnType("NUMBER(1)");

                    b.Property<bool>("IsGroup")
                        .HasColumnType("NUMBER(1)");

                    b.Property<bool>("IsScientific")
                        .HasColumnType("NUMBER(1)");

                    b.Property<int>("LessonType")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("StudentWorkloadHours")
                        .HasColumnType("NUMBER(10)");

                    b.Property<Guid?>("SubjectId")
                        .HasColumnType("RAW(16)");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.ToTable("Lesson");
                });

            modelBuilder.Entity("SyllabusManager.Data.Models.Subjects.Literature", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Authors")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Distributor")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("Isbn")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<Guid?>("SubjectId")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("Year")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.ToTable("Literature");
                });

            modelBuilder.Entity("SyllabusManager.Data.Models.Subjects.Subject", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("AcademicYear")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Discriminator")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("NUMBER(1)");

                    b.Property<int>("KindOfSubject")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("Language")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("ModuleType")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("NameEng")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("NamePl")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("SupervisorId")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<int>("TypeOfSubject")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.HasIndex("SupervisorId");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("SyllabusManager.Data.Models.Syllabuses.SubjectInSyllabusDescription", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("RAW(16)");

                    b.Property<int>("AssignedSemester")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("CompletionSemester")
                        .HasColumnType("NUMBER(10)");

                    b.Property<Guid?>("SubjectId")
                        .HasColumnType("RAW(16)");

                    b.Property<Guid?>("SyllabusId")
                        .HasColumnType("RAW(16)");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.HasIndex("SyllabusId");

                    b.ToTable("SubjectInSyllabusDescription");
                });

            modelBuilder.Entity("SyllabusManager.Data.Models.Syllabuses.Syllabus", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("AcademicYear")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime?>("ApprovalDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("DeanName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<Guid?>("DescriptionId")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("FieldOfStudyCode")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("IntershipType")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("NUMBER(1)");

                    b.Property<DateTime?>("OpinionDeadline")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("ScopeOfDiplomaExam")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("StudentGovernmentOpinion")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("StudentRepresentativeName")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime?>("ValidFrom")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.HasIndex("DescriptionId");

                    b.HasIndex("FieldOfStudyCode");

                    b.ToTable("Syllabuses");
                });

            modelBuilder.Entity("SyllabusManager.Data.Models.Syllabuses.SyllabusDescription", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("RAW(16)");

                    b.Property<int>("Ects")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("EmploymentOpportunities")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("FormOfGraduation")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("NumOfSemesters")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("PossibilityOfContinuation")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Prerequisites")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("ProfessionalTitleAfterGraduation")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.ToTable("SyllabusDescription");
                });

            modelBuilder.Entity("SyllabusManager.Data.Models.User.SyllabusManagerUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Email")
                        .HasColumnType("NVARCHAR2(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("NUMBER(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("NUMBER(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("NVARCHAR2(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("NVARCHAR2(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("UserName")
                        .HasColumnType("NVARCHAR2(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("SyllabusManager.Data.Models.User.SyllabusManagerUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("SyllabusManager.Data.Models.User.SyllabusManagerUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SyllabusManager.Data.Models.User.SyllabusManagerUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("SyllabusManager.Data.Models.User.SyllabusManagerUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SyllabusManager.Data.Models.FieldOfStudies.FieldOfStudy", b =>
                {
                    b.HasOne("SyllabusManager.Data.Models.User.SyllabusManagerUser", "Supervisor")
                        .WithMany()
                        .HasForeignKey("SupervisorId");
                });

            modelBuilder.Entity("SyllabusManager.Data.Models.FieldOfStudies.Specialization", b =>
                {
                    b.HasOne("SyllabusManager.Data.Models.FieldOfStudies.FieldOfStudy", null)
                        .WithMany("Specializations")
                        .HasForeignKey("FieldOfStudyCode");
                });

            modelBuilder.Entity("SyllabusManager.Data.Models.LearningOutcomes.LearningOutcome", b =>
                {
                    b.HasOne("SyllabusManager.Data.Models.LearningOutcomes.LearningOutcomeDocument", null)
                        .WithMany("LearningOutcomes")
                        .HasForeignKey("LearningOutcomeDocumentId");

                    b.HasOne("SyllabusManager.Data.Models.FieldOfStudies.Specialization", "Specialization")
                        .WithMany()
                        .HasForeignKey("SpecializationCode");
                });

            modelBuilder.Entity("SyllabusManager.Data.Models.LearningOutcomes.LearningOutcomeDocument", b =>
                {
                    b.HasOne("SyllabusManager.Data.Models.FieldOfStudies.FieldOfStudy", "FieldOfStudy")
                        .WithMany()
                        .HasForeignKey("FieldOfStudyCode");
                });

            modelBuilder.Entity("SyllabusManager.Data.Models.Subjects.CardEntries", b =>
                {
                    b.HasOne("SyllabusManager.Data.Models.Subjects.Subject", null)
                        .WithMany("CardEntries")
                        .HasForeignKey("SubjectId");
                });

            modelBuilder.Entity("SyllabusManager.Data.Models.Subjects.CardEntry", b =>
                {
                    b.HasOne("SyllabusManager.Data.Models.Subjects.CardEntries", null)
                        .WithMany("Entries")
                        .HasForeignKey("CardEntriesId");
                });

            modelBuilder.Entity("SyllabusManager.Data.Models.Subjects.ClassForm", b =>
                {
                    b.HasOne("SyllabusManager.Data.Models.Subjects.Lesson", null)
                        .WithMany("ClassForms")
                        .HasForeignKey("LessonId");
                });

            modelBuilder.Entity("SyllabusManager.Data.Models.Subjects.LearningOutcomeEvaluation", b =>
                {
                    b.HasOne("SyllabusManager.Data.Models.Subjects.Subject", null)
                        .WithMany("LearningOutcomeEvaluations")
                        .HasForeignKey("SubjectId");
                });

            modelBuilder.Entity("SyllabusManager.Data.Models.Subjects.Lesson", b =>
                {
                    b.HasOne("SyllabusManager.Data.Models.Subjects.Subject", null)
                        .WithMany("Lessons")
                        .HasForeignKey("SubjectId");
                });

            modelBuilder.Entity("SyllabusManager.Data.Models.Subjects.Literature", b =>
                {
                    b.HasOne("SyllabusManager.Data.Models.Subjects.Subject", null)
                        .WithMany("Literature")
                        .HasForeignKey("SubjectId");
                });

            modelBuilder.Entity("SyllabusManager.Data.Models.Subjects.Subject", b =>
                {
                    b.HasOne("SyllabusManager.Data.Models.User.SyllabusManagerUser", "Supervisor")
                        .WithMany()
                        .HasForeignKey("SupervisorId");
                });

            modelBuilder.Entity("SyllabusManager.Data.Models.Syllabuses.SubjectInSyllabusDescription", b =>
                {
                    b.HasOne("SyllabusManager.Data.Models.Subjects.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId");

                    b.HasOne("SyllabusManager.Data.Models.Syllabuses.Syllabus", null)
                        .WithMany("SubjectDescriptions")
                        .HasForeignKey("SyllabusId");
                });

            modelBuilder.Entity("SyllabusManager.Data.Models.Syllabuses.Syllabus", b =>
                {
                    b.HasOne("SyllabusManager.Data.Models.Syllabuses.SyllabusDescription", "Description")
                        .WithMany()
                        .HasForeignKey("DescriptionId");

                    b.HasOne("SyllabusManager.Data.Models.FieldOfStudies.FieldOfStudy", "FieldOfStudy")
                        .WithMany()
                        .HasForeignKey("FieldOfStudyCode");
                });
#pragma warning restore 612, 618
        }
    }
}
