# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Depoly backend to Azure


env:
  AZURE_WEBAPP_NAME: psi-syllabus-manager    # set this to your application's name
  DOTNET_ROOT: src/backend/SyllabusManager.API      # set this to the path to your web app project, defaults to the repository root
  PROJ_PATH: src/backend/SyllabusManager.API/SyllabusManager.API.csproj
  DOTNET_VERSION: '5.0'           # set this to the dot net version to use

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: Build with dotnet
      run: dotnet build ${{env.PROJ_PATH}} --configuration Release

    - name: dotnet publish
      run: dotnet publish ${{env.PROJ_PATH}} -c Release -o ${{env.DOTNET_ROOT}}/myapp

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'psi-syllabus-manager'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_ae592de7c2fe42049ffc5cd36d69d8de }}
        package: ${{env.DOTNET_ROOT}}/myapp 
